(ns clj-manifold3d.journal.schema)

;; One typed schema; DataScript omits scalar type declarations.
(def attributes
  {:document/id [:db.type/string :identity]
   :document/namespace [:db.type/string :identity]
   :document/ns-source [:db.type/string]
   :document/title [:db.type/string]
   :document/revision [:db.type/long]
   :document/instructions [:db.type/string]
   :document/instructions-mode [:db.type/string]
   :document/saved-content [:db.type/string]
   :document/deleted-panels [:db.type/string]
   :document/blocks [:db.type/ref :many]
   :document/applied-requests [:db.type/string :many]
   :block/id [:db.type/string :identity]
   :block/kind [:db.type/string]
   :block/order [:db.type/long]
   :block/source [:db.type/string]
   :block/hidden? [:db.type/boolean]
   :block/prompt-id [:db.type/string]
   :block/context-settings [:db.type/string]
   :block/viewer [:db.type/string]
   :block/generation-status [:db.type/string]
   :block/generation-message [:db.type/string]
   :workspace/id [:db.type/string :identity]
   :workspace/active-pane [:db.type/string]
   :workspace/vim? [:db.type/boolean]
   :workspace/instructions [:db.type/string]
   :workspace/codex-model [:db.type/string]
   :codex/id [:db.type/string :identity]
   :codex/models [:db.type/string]
   :codex/error [:db.type/string]
   :codex/loading? [:db.type/boolean]
   :library/id [:db.type/string :identity]
   :library/catalog [:db.type/string]
   :pane/id [:db.type/string :identity]
   :pane/document [:db.type/ref]
   :pane/order [:db.type/long]
   :pane/width [:db.type/double]
   ;; Transient browser facts use the same vocabulary, never persisted results.
   :ui/engine [:db.type/string]
   :ui/save-status [:db.type/string]
   :ui/active-block [:db.type/string]
   :ui/saved-layout [:db.type/string]
   :ui/request-id [:db.type/string]
   :ui/request-document [:db.type/string]
   :ui/session-cursor [:db.type/long]
   :ui/dialog [:db.type/string]
   :ui/draft-namespace [:db.type/string]
   :ui/draft-title [:db.type/string]
   :ui/dialog-error [:db.type/string]
   :ui/context-namespace [:db.type/string]
   :ui/context-prompt [:db.type/string]
   :ui/context-request [:db.type/string]
   :ui/context-inspection [:db.type/string]
   :ui/context-error [:db.type/string]
   :evaluation/namespace [:db.type/string :identity]
   :evaluation/history [:db.type/string]
   :result/id [:db.type/string :identity]
   :result/status [:db.type/string]
   :result/description [:db.type/string]
   :result/output [:db.type/string]
   :result/asset [:db.type/string]
   :result/polygons [:db.type/string]
   :result/wireframe? [:db.type/boolean]
   :result/paused? [:db.type/boolean]
   :result/tools? [:db.type/boolean]
   :result/measuring? [:db.type/boolean]
   :display/id [:db.type/string :identity]
   :display/mode [:db.type/string]
   :display/message [:db.type/string]
   :result/points [:db.type/string]
   :result/kind [:db.type/string]
   :request/id [:db.type/string :identity]
   :request/namespace [:db.type/string]
   :request/model [:db.type/string]
   :request/resolved-model [:db.type/string]
   :request/prompt-block [:db.type/string]
   :request/prompt [:db.type/string]
   :request/context [:db.type/string]
   :request/input [:db.type/string]
   :request/snapshot [:db.type/string]
   :request/previous-prompt [:db.type/string]
   :request/status [:db.type/string]
   :request/progress [:db.type/string]
   :request/output [:db.type/string]
   :request/preview [:db.type/string]
   :request/error [:db.type/string]
   :request/rejected-output [:db.type/string]
   :request/repair-input [:db.type/string]
   :request/repair-attempt [:db.type/long]
   :request/api-catalog [:db.type/string]
   :request/tool-log [:db.type/string]
   :request/evaluation-input [:db.type/string]
   :request/verification [:db.type/string]
   :request/verified-results [:db.type/string]
   :request/collaborative? [:db.type/boolean]
   :request/working-plan [:db.type/string]
   :request/turn-base [:db.type/string]
   :artifact/id [:db.type/string :identity]
   :artifact/request [:db.type/string]
   :artifact/bytes [:db.type/bytes]
   :request/created [:db.type/long]
   :request/updated [:db.type/long]
   :request/poll-error [:db.type/string]})

(def attribute-tx
  (mapv (fn [[ident [type option]]]
          (cond-> {:db/ident ident :db/valueType type
                   :db/cardinality (if (= option :many) :db.cardinality/many :db.cardinality/one)}
            (= option :identity) (assoc :db/unique :db.unique/identity))) attributes))

(def schema
  (into {} (map (fn [{:db/keys [ident valueType] :as attr}]
                  [ident (cond-> (dissoc attr :db/ident)
                           (not= valueType :db.type/ref) (dissoc :db/valueType))])
                attribute-tx)))
